
INSERT INTO CARTA_DE_NUMERO(0, amarillo, 0);
INSERT INTO CARTA_DE_NUMERO(1, amarillo, 1);
INSERT INTO CARTA_DE_NUMERO(2, amarillo, 2);
INSERT INTO CARTA_DE_NUMERO(3, amarillo, 3);
INSERT INTO CARTA_DE_NUMERO(4, amarillo, 4);
INSERT INTO CARTA_DE_NUMERO(5, amarillo, 5);
INSERT INTO CARTA_DE_NUMERO(6, amarillo, 6);
INSERT INTO CARTA_DE_NUMERO(7, amarillo, 7);
INSERT INTO CARTA_DE_NUMERO(8, amarillo, 8);
INSERT INTO CARTA_DE_NUMERO(9, amarillo, 9);

INSERT INTO CARTA_DE_NUMERO(10, verde, 0);
INSERT INTO CARTA_DE_NUMERO(11, verde, 1);
INSERT INTO CARTA_DE_NUMERO(12, verde, 2);
INSERT INTO CARTA_DE_NUMERO(13, verde, 3);
INSERT INTO CARTA_DE_NUMERO(14, verde, 4);
INSERT INTO CARTA_DE_NUMERO(15, verde, 5);
INSERT INTO CARTA_DE_NUMERO(16, verde, 6);
INSERT INTO CARTA_DE_NUMERO(17, verde, 7);
INSERT INTO CARTA_DE_NUMERO(18, verde, 8);
INSERT INTO CARTA_DE_NUMERO(19, verde, 9);

INSERT INTO CARTA_DE_NUMERO(20, rojo, 0);
INSERT INTO CARTA_DE_NUMERO(21, rojo, 1);
INSERT INTO CARTA_DE_NUMERO(22, rojo, 2);
INSERT INTO CARTA_DE_NUMERO(23, rojo, 3);
INSERT INTO CARTA_DE_NUMERO(24, rojo, 4);
INSERT INTO CARTA_DE_NUMERO(25, rojo, 5);
INSERT INTO CARTA_DE_NUMERO(26, rojo, 6);
INSERT INTO CARTA_DE_NUMERO(27, rojo, 7);
INSERT INTO CARTA_DE_NUMERO(28, rojo, 8);
INSERT INTO CARTA_DE_NUMERO(29, rojo, 9);

INSERT INTO CARTA_DE_NUMERO(30, azul, 0);
INSERT INTO CARTA_DE_NUMERO(31, azul, 1);
INSERT INTO CARTA_DE_NUMERO(32, azul, 2);
INSERT INTO CARTA_DE_NUMERO(33, azul, 3);
INSERT INTO CARTA_DE_NUMERO(34, azul, 4);
INSERT INTO CARTA_DE_NUMERO(35, azul, 5);
INSERT INTO CARTA_DE_NUMERO(36, azul, 6);
INSERT INTO CARTA_DE_NUMERO(37, azul, 7);
INSERT INTO CARTA_DE_NUMERO(38, azul, 8);
INSERT INTO CARTA_DE_NUMERO(39, azul, 9);


INSERT INTO CARTA_ESPECIAL_COLOR(40, amarillo, +2);
INSERT INTO CARTA_ESPECIAL_COLOR(41, verde, +2);
INSERT INTO CARTA_ESPECIAL_COLOR(42, rojo, +2);
INSERT INTO CARTA_ESPECIAL_COLOR(43, azul, +2);

INSERT INTO CARTA_ESPECIAL_COLOR(44, amarillo, 4);
INSERT INTO CARTA_ESPECIAL_COLOR(45, verde, 5);
INSERT INTO CARTA_ESPECIAL_COLOR(46, rojo, 6);
INSERT INTO CARTA_ESPECIAL_COLOR(47, azul, 7);

INSERT INTO CARTA_ESPECIAL_COLOR(48, amarillo, 8);
INSERT INTO CARTA_ESPECIAL_COLOR(49, verde, 9);
INSERT INTO CARTA_ESPECIAL_COLOR(50, rojo, 9);
INSERT INTO CARTA_ESPECIAL_COLOR(51, azul, 9);

